<a href="https://colab.research.google.com/github/manpreet1130/pytorch-speed-run/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

In [1]:
import torch

print(torch.__version__)

2.10.0+cpu


### Tensors

In [2]:
# scalar (named in lowercase)
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector (named in lowercase)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix (named in uppercase)

MATRIX = torch.tensor([[7, 8],
                       [1, 2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [9]:
MATRIX.ndim

2

In [10]:
# tensor (named in uppercase)
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9, 4],
                        [2, 2, 2, 4]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 4],
         [2, 2, 2, 4]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 4])

### Random Tensors

In [13]:
# create a random tensor of size/shape (3, 4)

random_tensor = torch.rand((3 ,4))
random_tensor

tensor([[0.5269, 0.9727, 0.9286, 0.5445],
        [0.9100, 0.8254, 0.2343, 0.6570],
        [0.5950, 0.7793, 0.7740, 0.8314]])

In [14]:
# create a random tensor with similar share to an image tensor
random_image_size_tensor = torch.rand((3, 224, 224)) # channels, height, width
random_image_size_tensor

tensor([[[0.4262, 0.1612, 0.4463,  ..., 0.1552, 0.2472, 0.2610],
         [0.4770, 0.7739, 0.2294,  ..., 0.6753, 0.8849, 0.0521],
         [0.3228, 0.3018, 0.4603,  ..., 0.8587, 0.8334, 0.0965],
         ...,
         [0.7598, 0.6383, 0.1221,  ..., 0.4944, 0.3971, 0.4286],
         [0.8312, 0.4127, 0.9164,  ..., 0.2052, 0.3257, 0.3047],
         [0.6311, 0.6042, 0.0343,  ..., 0.2867, 0.6465, 0.7986]],

        [[0.7781, 0.9890, 0.1769,  ..., 0.3721, 0.6476, 0.1456],
         [0.7441, 0.2577, 0.3744,  ..., 0.7596, 0.5719, 0.9817],
         [0.5997, 0.1770, 0.3786,  ..., 0.0332, 0.3452, 0.1200],
         ...,
         [0.4827, 0.7975, 0.6084,  ..., 0.1554, 0.4794, 0.0994],
         [0.2974, 0.7928, 0.3898,  ..., 0.3229, 0.7452, 0.4686],
         [0.5533, 0.2092, 0.7269,  ..., 0.9414, 0.2710, 0.4751]],

        [[0.3060, 0.1184, 0.1396,  ..., 0.1815, 0.3456, 0.4003],
         [0.6133, 0.2351, 0.0750,  ..., 0.7847, 0.9157, 0.2960],
         [0.6714, 0.0918, 0.1130,  ..., 0.5933, 0.3493, 0.

In [15]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [16]:
 # create a tensor with all zeros

zeros = torch.zeros((3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones((3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
# creating a range of tensors and tensors-like
even_numbers_from_0_to_100 = torch.arange(start = 0, end = 101, step = 2)
even_numbers_from_0_to_100

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100])

In [19]:
zeros_like = torch.zeros_like(input = even_numbers_from_0_to_100)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

### Tensor Datatypes

In [20]:
float_32_tensor = torch.tensor([[1, 2, 3],
                                [4, 5, 6]],
                               dtype=torch.float32,
                               device="cpu")
float_32_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

### Getting Information from Tensors

- Getting datatype: tensor.dtype
- Getting shape: tensor.shape
- Getting device: tensor.device


In [22]:
some_tensor = torch.rand(size=(3, 4), dtype=torch.float16)
some_tensor

tensor([[0.4897, 0.9370, 0.3691, 0.7290],
        [0.5820, 0.9121, 0.3726, 0.3545],
        [0.1152, 0.1597, 0.2729, 0.6592]], dtype=torch.float16)

In [23]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float16
torch.Size([3, 4])
cpu


### Tensor Operations

In [24]:
tensor = torch.rand(size=(1, 3))
tensor

tensor([[0.7979, 0.8288, 0.2499]])

In [25]:
mul_tensor = torch.mul(tensor, 10)
mul_tensor

tensor([[7.9789, 8.2880, 2.4989]])

In [26]:
# matrix multiplication (dot product)
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(tensor * tensor)
print(torch.matmul(tensor, tensor.T))
print(tensor @ tensor.T )

tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])


### Tensor Aggregation

In [27]:
tensor = torch.arange(0, 100, 10, dtype=torch.float32)
tensor.dtype

torch.float32

In [28]:
torch.min(tensor), tensor.min()

(tensor(0.), tensor(0.))

In [29]:
torch.mean(tensor), tensor.mean()

(tensor(45.), tensor(45.))

In [30]:
tensor = torch.arange(0, 11, dtype=torch.float32)
tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
argmin_tensor = torch.argmin(tensor) # returns index of target tensor with minvalue
argmax_tensor = torch.argmax(tensor) # returns index of target tensor with maxvalue
argmin_tensor, argmax_tensor

(tensor(0), tensor(10))

### Reshaping, Stacking, Squeezing and Unsqueezing
- reshaping: change input tensor shape to desired shape
- view: new tensor has the original tensor's address, any changes to new happen to old
- hstack: horizontal stack
- vstack: vertical stack
- squeeze: remove all 1 dimensions from a tensor
- unsqueeze: add a 1 dimension to a target tensor
- permute: return input where dimensions are swapped in a certain way

In [32]:
tensor = torch.arange(1., 10.)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [33]:
tensor_reshaped = tensor.reshape(3, 3)
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [34]:
tensor_view = tensor.view(9, 1)
tensor_view, tensor_view.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [35]:
# stacking
tensor_stack = torch.stack([tensor, tensor, tensor], dim = 1)
tensor.shape, tensor_stack, tensor_stack.shape

(torch.Size([9]),
 tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 torch.Size([9, 3]))

In [36]:
tensor_vstack = torch.vstack([tensor, tensor, tensor])
tensor_vstack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [37]:
tensor_hstack = torch.hstack([tensor, tensor, tensor])
tensor_hstack

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
# squeeze
tensor = torch.reshape(tensor, (1, 1, 9))
tensor, tensor.shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [39]:
tensor_squeezed = torch.squeeze(tensor)
tensor_squeezed, tensor_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
tensor_unsqueezed = torch.unsqueeze(tensor_squeezed, dim = 0)
tensor_unsqueezed = torch.unsqueeze(tensor_unsqueezed, dim = 2)
tensor_unsqueezed, tensor_unsqueezed.shape

(tensor([[[1.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

In [54]:
# torch.permute - it a view, so same memory as original tensor
tensor = torch.rand((224, 224, 3))
permuted_tensor = tensor.permute(2, 0, 1)
tensor.shape, permuted_tensor.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## PyTorch and NumPy




In [60]:
import numpy as np

arr = np.arange(1, 8)
# numpy default is float64 but pytorch default is float32
tensor = torch.from_numpy(arr).type(torch.float32)
arr, tensor, tensor.dtype

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [66]:
# tensor to numpy
tensor = torch.ones(7)
# numpy default is float64, pytorch default is float32
numpy_tensor = tensor.numpy().astype(np.float64)
tensor, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.]),
 dtype('float64'))

### Reproducibility

In [69]:
# create two random tensors
a = torch.rand(3, 4)
b = torch.rand(3, 4)
print(a)
print(b)
print(a == b)

tensor([[0.4686, 0.7941, 0.7214, 0.0093],
        [0.8291, 0.8728, 0.7137, 0.3016],
        [0.9845, 0.3702, 0.4905, 0.5945]])
tensor([[0.1871, 0.4325, 0.1184, 0.6881],
        [0.7850, 0.0215, 0.5258, 0.0947],
        [0.5373, 0.3730, 0.8918, 0.2901]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
# set a random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
a = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
b = torch.rand(3, 4)
print(a)
print(b)
print(a == b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [73]:
### GPU Access and Device Agnostic Code

In [75]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [77]:
# count the number of devices
torch.cuda.device_count()

0

In [81]:
# move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# move tensor back to cpu
tensor_on_cpu = tensor_on_gpu.cpu() # numpy doesn't work on gpu, only cpu
tensor_on_cpu


tensor([1., 1., 1., 1., 1., 1., 1.])